language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t sirasira/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sirasira/docker-react npm run test -- --coverage